-- ══════════════════════════════════════════════════════════════════════
-- تتبّع موقع السائقين (GPS) — يُشغَّل مرة واحدة
-- يُشغَّل في: Supabase ← المشروع الجديد ← SQL Editor ← Run
--
-- ١) جدول fleet_gps: نقاط موقع كل رحلة (يكتبها بوت تلجرام)، وتُحذف تلقائياً مع رحلتها
-- ٢) يقرؤها ويحذفها مسؤول التوصيل ومدير المبيعات والمطوّر فقط
-- ٣) يسمح لتذاكر البوت بالنوع الجديد 'g' (فتح التتبع من زرّ السائق)
-- ══════════════════════════════════════════════════════════════════════

do $$
declare ty text; c record; dropped boolean := false;
begin
  /* trip_id بنفس نوع معرّف الرحلة، ويُحذف مع الرحلة */
  select format_type(atttypid, atttypmod) into ty from pg_attribute
   where attrelid = 'public.fleet_trips'::regclass and attname = 'id';
  execute format('create table if not exists public.fleet_gps (
      id bigint generated by default as identity primary key,
      trip_id %s not null references public.fleet_trips(id) on delete cascade,
      driver_id text,
      lat double precision not null,
      lng double precision not null,
      acc real,
      at timestamptz not null default now())', ty);

  /* إن كان عمود action في التذاكر مقيَّداً بقائمة، نضيف إليها 'g' */
  for c in select conname from pg_constraint
            where conrelid = 'public.tg_tickets'::regclass and contype = 'c'
              and pg_get_constraintdef(oid) ilike '%action%' loop
    execute format('alter table public.tg_tickets drop constraint %I', c.conname);
    dropped := true;
  end loop;
  if dropped then
    alter table public.tg_tickets add constraint tg_tickets_action_check
      check (action in ('k', 'd', 'a', 'g'));
  end if;
end $$;

create index if not exists fleet_gps_trip_at on public.fleet_gps (trip_id, at);

alter table public.fleet_gps enable row level security;
drop policy if exists fleet_gps_read on public.fleet_gps;
drop policy if exists fleet_gps_del on public.fleet_gps;
create policy fleet_gps_read on public.fleet_gps for select to authenticated
  using (exists (select 1 from public.profiles p
                  where p.id::text = auth.uid()::text and p.role in ('fleet', 'sales', 'dev')));
create policy fleet_gps_del on public.fleet_gps for delete to authenticated
  using (exists (select 1 from public.profiles p
                  where p.id::text = auth.uid()::text and p.role in ('fleet', 'sales', 'dev')));

select 'تم ✓ — جدول fleet_gps جاهز' as "النتيجة";
