-- ══════════════════════════════════════════════════════════════════════
-- أسباب وقفات السائق — يسأله البوت عن كل وقفة تتجاوز ٣ دقائق ويحفظ جوابه هنا
-- يُشغَّل مرة واحدة بعد 03_fleet_gps.sql
-- ══════════════════════════════════════════════════════════════════════
do $$
declare ty text;
begin
  select format_type(atttypid, atttypmod) into ty from pg_attribute
   where attrelid = 'public.fleet_trips'::regclass and attname = 'id';
  execute format('create table if not exists public.fleet_stop_reasons (
      id bigint generated by default as identity primary key,
      trip_id %s not null references public.fleet_trips(id) on delete cascade,
      from_s bigint not null,            -- بداية الوقفة (ثوانٍ) — تطابق الوقفة في التطبيق
      from_at timestamptz,
      lat double precision, lng double precision,
      driver_id text,
      reason text,                       -- فارغ = سُئل ولم يُجب بعد
      answered_at timestamptz,
      unique (trip_id, from_s))', ty);
end $$;

alter table public.fleet_stop_reasons enable row level security;
drop policy if exists fleet_stop_reasons_read on public.fleet_stop_reasons;
create policy fleet_stop_reasons_read on public.fleet_stop_reasons for select to authenticated
  using (exists (select 1 from public.profiles p
                  where p.id::text = auth.uid()::text and p.role in ('fleet', 'sales', 'dev')));

select 'تم ✓ — جدول أسباب الوقفات جاهز' as "النتيجة";
