-- ══════════════════════════════════════════════════════════════════════
-- جدول تدقيق اليوم — يراه ويكتبه مسؤول تدقيق التوصيل وحده
-- (دوره fleet مثل مسؤول التوصيل وآلياته، ويتميّز بكلمة «تدقيق» في مسمّاه الوظيفي)
-- بعد «القفل النهائي» ترفض القاعدة نفسها أي تعديل (لا الشاشة فقط)
-- يُشغَّل مرة واحدة — آمن إن شُغّل أكثر من مرة
-- ══════════════════════════════════════════════════════════════════════
create table if not exists public.fleet_day_audit (
  id bigint generated by default as identity primary key,
  day date not null,                 -- يوم الشفت
  driver_id text not null,
  driver_name text,
  data jsonb not null default '{}'::jsonb,   -- البصمات، الفواتير، الملاحظات، المجهز...
  updated_at timestamptz default now(),
  updated_by text, updated_by_name text,
  locked_at timestamptz, locked_by text, locked_by_name text,
  unique (day, driver_id)
);

alter table public.fleet_day_audit enable row level security;
drop policy if exists fda_read on public.fleet_day_audit;
drop policy if exists fda_ins on public.fleet_day_audit;
drop policy if exists fda_upd on public.fleet_day_audit;
create policy fda_read on public.fleet_day_audit for select to authenticated
  using (exists (select 1 from public.profiles p where p.id::text = auth.uid()::text and p.role = 'fleet' and p.job_title like '%تدقيق%'));
create policy fda_ins on public.fleet_day_audit for insert to authenticated
  with check (exists (select 1 from public.profiles p where p.id::text = auth.uid()::text and p.role = 'fleet' and p.job_title like '%تدقيق%'));
create policy fda_upd on public.fleet_day_audit for update to authenticated
  using (locked_at is null
         and exists (select 1 from public.profiles p where p.id::text = auth.uid()::text and p.role = 'fleet' and p.job_title like '%تدقيق%'))
  with check (exists (select 1 from public.profiles p where p.id::text = auth.uid()::text and p.role = 'fleet' and p.job_title like '%تدقيق%'));

/* من يرى الجدول؟ — يجب أن يظهر هنا مسؤول تدقيق التوصيل وحده */
select name as "الاسم", job_title as "المسمّى",
       case when job_title like '%تدقيق%' then '✓ يرى الجدول' else '✗ لا يراه' end as "جدول اليوم"
  from public.profiles where role = 'fleet' order by 3, 1;
