-- ══════════════════════════════════════════════════════════════════════
-- انقطاع موقع السائق: سجلّ التنبيهات + مؤقّت يفحص كل دقيقتين
-- آمن إن شُغّل أكثر من مرة
--
-- ١) جدول fleet_gps_alerts: كل انقطاع (أوقف المشاركة / توقّف الإرسال / لم يشارك)
--    مع عدد التنبيهات التي وصلت السائق ووقت عودة الموقع
-- ٢) يقرؤه مسؤولو التوصيل ومدير المبيعات والمطوّر، والسائق يقرأ انقطاعاته فقط
-- ٣) مؤقّت pg_cron يستدعي البوت كل دقيقتين ليكتشف توقّف الموقع وينبّه السائق
-- ══════════════════════════════════════════════════════════════════════

do $$
declare ty text;
begin
  select format_type(atttypid, atttypmod) into ty from pg_attribute
   where attrelid = 'public.fleet_trips'::regclass and attname = 'id';
  execute format('create table if not exists public.fleet_gps_alerts (
      id bigint generated by default as identity primary key,
      trip_id %s not null references public.fleet_trips(id) on delete cascade,
      driver_id text,
      driver_name text,
      kind text not null,                -- stop: أوقف المشاركة · lost: توقّف الإرسال · none: لم يشارك
      from_at timestamptz not null,      -- آخر موقع وصل قبل الانقطاع
      warns int not null default 0,      -- عدد التنبيهات التي أُرسلت للسائق
      last_warn_at timestamptz,
      resumed_at timestamptz,            -- فارغ = ما زال منقطعاً
      created_at timestamptz not null default now())', ty);
end $$;
create index if not exists fleet_gps_alerts_trip on public.fleet_gps_alerts (trip_id, resumed_at);

alter table public.fleet_gps_alerts enable row level security;
drop policy if exists fleet_gps_alerts_read on public.fleet_gps_alerts;
create policy fleet_gps_alerts_read on public.fleet_gps_alerts for select to authenticated
  using (exists (select 1 from public.profiles p
                  where p.id::text = auth.uid()::text and p.role in ('fleet', 'sales', 'dev')));
drop policy if exists fleet_gps_alerts_read_own on public.fleet_gps_alerts;
create policy fleet_gps_alerts_read_own on public.fleet_gps_alerts for select to authenticated
  using (driver_id = auth.uid()::text);

/* المؤقّت: كل دقيقتين يطلب من البوت فحص الرحلات المفتوحة */
create extension if not exists pg_cron;
create extension if not exists pg_net;
do $$
begin
  perform cron.unschedule(jobid) from cron.job where jobname = 'gps-watch';
end $$;
select cron.schedule('gps-watch', '*/2 * * * *',
  $$ select net.http_get('https://lfkifdlvafoziznrlham.supabase.co/functions/v1/tg-bot?cron=gps') $$);

select 'تم ✓ — تنبيه انقطاع الموقع يعمل كل دقيقتين' as "النتيجة";
